### ISSUE TITLE
After re-render tabs invalid scrollable tabs width

### ISSUE THREAD

**Issue by movie4** [happypancake/react-native-scrollable-tab-view#443]
Hello!

After re-render  tabs invalid scrollable tabs width

fix with monkey patch

```
if (this.state.categories[0].name === 'all' ) {
      return (
        <View></View>
      )
    } else {
      return (
        <View>
          {this.renderModal()}
          <ScrollableTabView renderTabBar={this.renderTabBar}>
            {this.renderCategoriesTabs()}
          </ScrollableTabView>
        </View>
      )
    }
```

Thanks for great app!

**Comment by skv-headless** [comment]
Can you please reproduce on example https://github.com/skv-headless/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/DynamicExample.js? PR showing this bug would be awesome.

**Comment by ChangeSomeCode** [comment]
This problem is solved in PR #362. If you make a new release, it will be nice.

**Comment by summersky92** [comment]
@ChangeSomeCode  Thx for the info! I also encounter this problem now see the PR solve.

**Comment by trinadhkoya** [comment]
Still have an issue ,width chages dramatically,(taking the previous view's width)
